export { default as Nav } from "./common/Nav"
export { default as Footer } from "./common/Footer"
export { default as SingleLink } from "./common/SingleLink"
export { default as SectionTitle } from "./common/SectionTitle"
export { default as Divider } from "./common/Divider"
export { default as PaginationControls } from "./common/PaginationControls"
export { default as CTA } from "./common/CTA"
export { default as Loader } from "./common/Loader"
export { default as ComingSoon } from "./common/ComingSoon"
export { default as MobileTabNav } from "./common/MobileTabNav"
export { default as Logo } from "./common/Logo"

export { default as Hero } from "./Home/Hero"
export { default as CategorySec } from "./Home/CategorySec"
export { default as PromisesSec } from "./Home/PromisesSec"
export { default as FeaturedSec } from "./Home/FeaturedSec"
export { default as DiamondSec } from "./Home/DiamondSec"
export { default as MensSec } from "./Home/MensSec"
export { default as StoreLocationSec } from "./Home/StoreLocationSec"
export { default as GallerySec } from "./Home/GallerySec"
export { default as HeroMobile } from "./Home/HeroMobile"
export { default as StoryCarousel } from "./Home/StoryCarousel"

export { default as Filters } from "./Jewellery/Filters"
export { default as Banner } from "./Jewellery/Banner"
export { default as ItemList } from "./Jewellery/ItemList"
export { default as JewelleryDetails } from "./Jewellery/JewelleryDetails"
export { default as ProductImages } from "./Jewellery/ProductImages"

export { default as SideNavbar } from "./Dashboard/SideNavbar"
export { default as Navlinks } from "./Dashboard/Navlinks"
export { default as NotificationContainer } from "./Dashboard/NotificationContainer"
export { default as Header } from "./Dashboard/Header"

export { default as SignupForm } from "./auth/SignupForm"
export { default as SigninForm } from "./auth/SigninForm"

export { default as AboutUs } from "./About/AboutUs"

export { default as ContactForm } from "./Contact/ContactForm"

export { default as Policies } from "./StaticPages/Policies"